import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#001b3e",
        "surface-container-lowest": "#0b0e15",
        "on-surface-variant": "#c1c6d6",
        "inverse-primary": "#005cba",
        "secondary-container": "#42474f",
        "primary-container": "#418fff",
        "on-primary-container": "#002959",
        "on-secondary": "#2c3138",
        "surface-tint": "#aac7ff",
        "outline-variant": "#414753",
        tertiary: "#c6c6cc",
        "inverse-surface": "#e0e2ec",
        "tertiary-fixed": "#e2e2e8",
        "on-tertiary-container": "#282a2e",
        "tertiary-container": "#8f9096",
        outline: "#8b919f",
        error: "#ffb4ab",
        background: "#10131a",
        "tertiary-fixed-dim": "#c6c6cc",
        "surface-dim": "#10131a",
        "secondary-fixed": "#dee2ec",
        "surface-variant": "#32353c",
        "on-primary-fixed-variant": "#00458e",
        "surface-container-low": "#181c22",
        secondary: "#c2c7d0",
        "on-background": "#e0e2ec",
        "surface-container-high": "#272a31",
        "secondary-fixed-dim": "#c2c7d0",
        "error-container": "#93000a",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
        "inverse-on-surface": "#2d3038",
        surface: "#10131a",
        "on-secondary-fixed-variant": "#42474f",
        primary: "#aac7ff",
        "surface-container": "#1c2027",
        "on-surface": "#e0e2ec",
        "primary-fixed-dim": "#aac7ff",
        "on-tertiary": "#2f3035",
        "primary-fixed": "#d7e3ff",
        "on-primary": "#002f65",
        "surface-container-highest": "#32353c",
        "on-secondary-container": "#b1b5bf",
        "surface-bright": "#363941",
        "on-tertiary-fixed": "#1a1c20",
        "on-secondary-fixed": "#171c23",
        "on-tertiary-fixed-variant": "#45474b",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        gutter: "16px",
        unit: "4px",
        margin: "24px",
        "density-high": "8px",
        "density-med": "16px",
      },
      fontFamily: {
        "data-metric": ["JetBrains Mono", "monospace"],
        "display-lg": ["Inter", "sans-serif"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "reasoning-log": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "data-metric": ["16px", { lineHeight: "24px", letterSpacing: "0.02em", fontWeight: "500" }],
        "display-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "reasoning-log": ["13px", { lineHeight: "18px", fontWeight: "400" }],
      },
    },
  },
};

export default config;
